### ISSUE TITLE
4 WD packet serial connection

### ISSUE THREAD

**Issue by BooraKaushik** [dumbotics/roboclaw_hardware_interface#10]
Hi @coxep, I have 2 roboclaws one controlling the 2 forward wheels and another controlling the back wheels, I am trying to connect them in packet serial mode, do you have some documentation shedding light on how to do that?

**Comment by coxep** [comment]
Check out bridged mode in the user manual (page 49): https://downloads.basicmicro.com/docs/roboclaw_user_manual.pdf

**Comment by coxep** [comment]
Disregard the prior comment.

@BooraKaushik checkout this: https://resources.basicmicro.com/using-multiple-roboclaws-with-arduino/

**Comment by coxep** [comment]
@BooraKaushik Here's another one that might be more relevant: https://resources.basicmicro.com/packet-serial-bus-operation-with-the-raspberry-pi-3/

I haven't done this myself, so curious to see how well it works. If you get it up and running, I'd love to feature instructions for 4+ WD on the readme

**Comment by coxep** [comment]
@BooraKaushik one final link: https://forums.basicmicro.com/viewtopic.php?t=442

Seems possible to set one device to master and the other to multi-unit mode to control both over a single USB connection. Good luck!

**Comment by coxep** [comment]
@BooraKaushik did you get this resolved?

**Comment by BooraKaushik** [comment]
Hi eric sorry, forgot to give you an update. Seems like one of my roboclaws got damaged so it might take some more time for me to test.

**Comment by BooraKaushik** [comment]
Hi @coxep ,
I have 2 Roboclaw Motor Controllers 2*30A, I am trying to connect them serially using the Packet Serial mode so that I can control both the roboclaws using 1 USB. I have tried the following, but it seems not to work.
Approach:
Set the one unit to Relay mode(but not to Multi-unit mode).
Set the other unit to Multi-Unit and Relay mode and change to a non conflicting address in My case (master is set to 128 and slave is set 129).
Connect S1 on the master to the slave's S2.
Connect S2 on the master to the slave's  S1.
I have connected the USB to Master to check if I could see both Port 128 and 129 come up on app, and they don't.

I tried setting both to relay mode and MultiUnit Mode and set both in relay Mode as well but seems like it doesn't work.
I checked out the documentation that you have provided in which all of them describe the above approach Do you know whats wrong here?.

Thanks,
Kaushik

**Comment by coxep** [comment]
Hi @BooraKaushik , could you setting the first unit (USB) to relay mode, and leave multi-unit AND relay mode unchecked for the second roboclaw. Also check that the addresses for the two units are different

**Comment by BooraKaushik** [comment]
@coxep That actually worked, thanks a lot. Now I am able to see both my roboclaws on the Basicmicro Motion studio app. I will try and see if the commands work and update you

**Comment by BooraKaushik** [comment]
@coxep I am getting the following error when I try to run dumbot_bringup

[ros2_control_node-1] [INFO] [1713059972.077669636] [controller_manager]: update rate is 100 Hz
[ros2_control_node-1] terminate called after throwing an instance of 'std::runtime_error'
[ros2_control_node-1]   what():  Read timeout!

**Comment by coxep** [comment]
> @coxep I am getting the following error when I try to run dumbot_bringup
> 
> [ros2_control_node-1] [INFO] [1713059972.077669636] [controller_manager]: update rate is 100 Hz
> [ros2_control_node-1] terminate called after throwing an instance of 'std::runtime_error'
> [ros2_control_node-1]   what():  Read timeout!

Dumbot_bringup doesn't support 4wd out of the box. It is a model of a 2wd robot.

You could try double checking the PID params, serial address, serial device. I'd try checking sending requests and getting feedback for each roboclaw unit (same USB port, different serial address) using dumbot bringup.

If this works for each motors pair, I can help you extend dumbot bring up support for 4wd

**Comment by BooraKaushik** [comment]
Hi @coxep,
I have set only one address as of now so isn't it like a 2WD, so theoretically shouldn't it be able to drive the front two wheels?

EDIT:
So I have tested it with by disconnecting the other motor controller seems like the standalone one works fine its just that when the other motor controller is connected it is not able to communicate with either. 

Can we connect today @coxep if you have time ?

**Comment by coxep** [comment]
Yes, in theory it should drive the front pair of wheels in the
multi-roboclaw configuration.

Do other drivers you've used (such as roboclaw's python3 library) work with
the multi-roboclaw configuration?

I don't have availability today unfortunately. Do you have some time this
weekend?

**Comment by BooraKaushik** [comment]
Yeah @coxep, seems like when multiple roboclaws are connected the library can't read/write data onto them. I tried using the default roboclaw python library and all four wheels seem to run. yeah, the weekend works for me.

**Comment by coxep** [comment]
Ok, that's great news! We should be able to get this working then

**Comment by BooraKaushik** [comment]
Okay @coxep, when do you want to connect in the weekend?

**Comment by coxep** [comment]
> Okay @coxep, when do you want to connect in the weekend?
> 

Sent you an email

**Comment by coxep** [comment]
@BooraKaushik any updates on your end for this? Did you get support from BasicMicro?

**Comment by bogdan-abaza** [comment]
I'm building a new robot with 4 DC gobilda 223 RPM and I'm thinking to use 2 x RoboClaw 2x15A Motor Controllers. There is any advice based on this development?

**Comment by coxep** [comment]
> I'm building a new robot with 4 DC gobilda 223 RPM and I'm thinking to use 2 x RoboClaw 2x15A Motor Controllers. There is any advice based on this development?

Hi @bogdan-abaza , the recommended approach is to run two hardware interfaces in parallel (each managing a single roboclaw) and then use the differential drive controller as before, but update configuration to use all four wheels. Differential drive controller can handle this just fine.

Note that this is untested, but if you run into any issues, please let me know and I will help you resolve them!

@BooraKaushik tried (without success?) to get 4WD running by daisy-chaining one roboclaw unit to another, and communicate with the assembly over a single hardware interface. This would have been ideal, but did not work well.
