### ISSUE TITLE
MainBatteryVoltage

### ISSUE THREAD

**Issue by bogdanabaza** [dumbotics/roboclaw_hardware_interface#11]
There is any way how can be read and bring to ros2 the battery info like MainBatteryVoltage provided by the roboclaw controller using the same serial session?

**Comment by coxep** [comment]
Yes, this can definitely done using the same serial interface. The control
interface only handles reading and setting wheel speeds, but I can add an
example feature branch that publishes MainVoltage soon

**Comment by coxep** [comment]
I'll probably add a GPIO interface to parse battery (something like this: https://github.com/ros-controls/ros2_control/pull/436). Any other information you want me to add besides voltage?

**Comment by bogdanabaza** [comment]
Thank you for prompt response and availability. Another useful information could be: READ_M1_M2_CURRENT, READ_MAIN_BATT_VOLT_SET and about temperature READ_TEMP.

**Comment by coxep** [comment]
I locally modded the hardware interface to read battery and temp, and will use motor current to generate "effort" for each joint. There isn't an existing controller for broadcasting battery/temp (required to put the actual data into ROS), so I'm going to have to write one. Happy to do this because this is a nice feature that I'd like to have on my own robot, but just be aware this could take a few days

**Comment by coxep** [comment]
Just a quick update - I played around with this a little more tonight and have the basic roboclaw broadcaster created, loaded into the controller manager, and processing voltage and temperature messages from the hardware interface. Currently just spitting debug messages to terminal. I'll try to get this a little more cleaned up and publishing ROS2 messages over the next couple days...

```
eric@eric:~/robot_ws$ ros2 launch dumbot_bringup minimal.launch.py 
[INFO] [launch]: All log files can be found below /home/eric/.ros/log/2024-08-02-00-33-01-534255-eric-200757
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [ros2_control_node-1]: process started with pid [200761]
[INFO] [robot_state_publisher-2]: process started with pid [200763]
[INFO] [spawner-3]: process started with pid [200765]
[INFO] [spawner-4]: process started with pid [200767]
[INFO] [spawner-5]: process started with pid [200769]
[ros2_control_node-1] [WARN] [1722573181.834095708] [controller_manager]: [Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
[ros2_control_node-1] [INFO] [1722573181.834250252] [resource_manager]: Loading hardware 'roboclaw_controller' 
[ros2_control_node-1] [INFO] [1722573181.834850197] [resource_manager]: Initialize hardware 'roboclaw_controller' 
[ros2_control_node-1] [INFO] [1722573181.835404809] [resource_manager]: Successful initialization of hardware 'roboclaw_controller'
[ros2_control_node-1] [INFO] [1722573181.835521153] [resource_manager]: 'configure' hardware '' 
[ros2_control_node-1] [INFO] [1722573181.835527184] [resource_manager]: Successful 'configure' of hardware ''
[ros2_control_node-1] [INFO] [1722573181.835531061] [resource_manager]: 'activate' hardware '' 
[ros2_control_node-1] [INFO] [1722573181.835535219] [resource_manager]: Successful 'activate' of hardware ''
[ros2_control_node-1] [INFO] [1722573181.838903782] [controller_manager]: update rate is 100 Hz
[ros2_control_node-1] [INFO] [1722573181.839362717] [controller_manager]: RT kernel is recommended for better performance
[robot_state_publisher-2] [INFO] [1722573181.854038833] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-2] [INFO] [1722573181.854158704] [robot_state_publisher]: got segment base_link
[robot_state_publisher-2] [INFO] [1722573181.854167240] [robot_state_publisher]: got segment caster_left_wheel
[robot_state_publisher-2] [INFO] [1722573181.854172099] [robot_state_publisher]: got segment caster_right_wheel
[robot_state_publisher-2] [INFO] [1722573181.854176086] [robot_state_publisher]: got segment left_wheel
[robot_state_publisher-2] [INFO] [1722573181.854180113] [robot_state_publisher]: got segment right_wheel
[ros2_control_node-1] [INFO] [1722573182.091566122] [controller_manager]: Loading controller 'diffbot_base_controller'
[ros2_control_node-1] [INFO] [1722573182.105254510] [controller_manager]: Loading controller 'joint_state_broadcaster'
[ros2_control_node-1] [INFO] [1722573182.113411372] [controller_manager]: Loading controller 'roboclaw_broadcaster'
[spawner-4] [INFO] [1722573182.114490569] [spawner_diffbot_base_controller]: Loaded diffbot_base_controller
[ros2_control_node-1] Init!
[ros2_control_node-1] [INFO] [1722573182.120973488] [controller_manager]: Configuring controller 'diffbot_base_controller'
[spawner-3] [INFO] [1722573182.125571185] [spawner_joint_state_broadcaster]: Loaded joint_state_broadcaster
[ros2_control_node-1] [INFO] [1722573182.130642384] [controller_manager]: Configuring controller 'joint_state_broadcaster'
[ros2_control_node-1] [INFO] [1722573182.130695251] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[spawner-5] [INFO] [1722573182.135670404] [spawner_roboclaw_broadcaster]: Loaded roboclaw_broadcaster
[ros2_control_node-1] [INFO] [1722573182.140887271] [controller_manager]: Configuring controller 'roboclaw_broadcaster'
[ros2_control_node-1] Cofigure!
[spawner-4] [INFO] [1722573182.171510636] [spawner_diffbot_base_controller]: Configured and activated diffbot_base_controller
[spawner-3] [INFO] [1722573182.191450546] [spawner_joint_state_broadcaster]: Configured and activated joint_state_broadcaster
[ros2_control_node-1] [INFO] [1722573182.210617774] [roboclaw_broadcaster]: Voltage: 25.500000
[ros2_control_node-1] [INFO] [1722573182.210696529] [roboclaw_broadcaster]: Temperature: 21.700000
[spawner-5] [INFO] [1722573182.211651057] [spawner_roboclaw_broadcaster]: Configured and activated roboclaw_broadcaster
[ros2_control_node-1] [INFO] [1722573182.220599046] [roboclaw_broadcaster]: Voltage: 25.500000
[ros2_control_node-1] [INFO] [1722573182.220668063] [roboclaw_broadcaster]: Temperature: 21.700000
[ros2_control_node-1] [INFO] [1722573182.230697683] [roboclaw_broadcaster]: Voltage: 25.500000
[ros2_control_node-1] [INFO] [1722573182.230800873] [roboclaw_broadcaster]: Temperature: 21.700000
[ros2_control_node-1] [INFO] [1722573182.240496378] [roboclaw_broadcaster]: Voltage: 25.500000
[ros2_control_node-1] [INFO] [1722573182.240539999] [roboclaw_broadcaster]: Temperature: 21.700000
[ros2_control_node-1] [INFO] [1722573182.250613780] [roboclaw_broadcaster]: Voltage: 25.500000
[ros2_control_node-1] [INFO] [1722573182.250677097] [roboclaw_broadcaster]: Temperature: 21.700000
[ros2_control_node-1] [INFO] [1722573182.260528599] [roboclaw_broadcaster]: Voltage: 25.500000
[ros2_control_node-1] [INFO] [1722573182.260553635] [roboclaw_broadcaster]: Temperature: 21.700000
...
```

**Comment by coxep** [comment]
@bogdanabaza can you give the [11-mainbatteryvoltage](https://github.com/dumbotics/roboclaw_hardware_interface/tree/11-mainbatteryvoltage) branch a shot? There is a matching branch for dumbot_bringup here: [11-mainbatteryvoltage](https://github.com/dumbotics/dumbot_bringup/tree/11-mainbatteryvoltage)

This add the following new/modified topics:

1. `/roboclaw_broadcaster/battery`
    - voltage (from main voltage reading)
    -  percentage (from main voltage and min/max cutoff readings)
2. `/roboclaw_broadcaster/temperature`
3. `/joint_states`
    - now includes "effort" for each joint, which defaults to the motor current in A if the motor constants for each joint aren't provided.

Not sure if you use multiple roboclaw units or not, but the changes currently assume just one roboclaw per hardware interface.

Give this a shot and if you're happy with it, I'll clean it up and pull it into main.

**Comment by bogdanabaza** [comment]
[colcon build warning.txt](https://github.com/user-attachments/files/16492098/colcon.build.warning.txt)
[ros2 topic echo.txt](https://github.com/user-attachments/files/16492100/ros2.topic.echo.txt)
I succeed to try branch "1-mainbatteryvoltage".
Attached are 2 txt files:
1. colcon.build.warning.txt - I got this when I build for the 1st time the [roboclaw_hardware_interface]
2. ros2.topic.echo.txt - the values in static position of the robot running minimal.launch.py

Now I will continue to test with my custom launch files.
Thank you again for your work!

**Comment by coxep** [comment]
My plan at this point is to add the broadcaster to a new `roboclaw_broadcaster` repository, and add a roboclaw_ros2_control monorepo that pulls in roboclaw_serial, hardware interface, broadcaster, and bringup packages as submodules. Closing this for now, but leaving the feature branch in place until I've made these changes.

@bogdanabaza if you do run into any issues during testing, please reopen this.
