### ISSUE TITLE
roboclaw_serial library

### ISSUE THREAD

**Issue by bogdanabaza** [dumbotics/roboclaw_hardware_interface#6]
Hello,
Regarding the step2 from Setup & Installation the link to roboclaw_serial library  is not functional.
[roboclaw_serial library](https://github.com/dumbotics/roboclaw_serial).
Can you update the link or provide an alternative pls.
Thank you,

**Comment by coxep** [comment]
Hi @bogdanabaza ,

Apologies for the delay. I've opened up the roboclaw_serial library. Please be advised that I've developed all of this very recently and there are probably bugs! Any feedback / additional issues are welcome.

https://github.com/dumbotics/roboclaw_serial
